### ISSUE TITLE
Get a Segwit address from Public Key

### ISSUE THREAD

**Issue by FontaineDenton** [oleganza/CoreBitcoin#104]
Has anyone successfully created a segwit address from a compressed public key? I have been trying like crazy but not been able to get it to work. I can create the segwit address but when i test it on segwitaddress.org with the WIF private key the segwit addresses do not match... Please any advice would be greatly appreciated.

**Comment by FontaineDenton** [comment]
I got it to work, by using this https://github.com/0xDEADP00L/Bech32/blob/master/Sources/Bech32.swift

**Comment by AlleniCode** [comment]
@FontaineDenton How to sig for a transaction with P2SH script UTXOs? Thx!
