### ISSUE TITLE
how to create BTCKeychain by privateKeyAddress ?

### ISSUE THREAD

**Issue by topws** [oleganza/CoreBitcoin#109]
how to create BTCKeychain by privateKeyAddress ?

**Comment by FontaineDenton** [comment]
`if let privateKey = BTCPrivateKeyAddress(string: yourWifPrivateKey) {
                        
                        if let key = BTCKey.init(privateKeyAddress: privateKey) {
                            
                            print("privateKey = \(key.privateKeyAddress)")
}

}`

**Comment by FontaineDenton** [comment]
`if let privateKey = BTCPrivateKeyAddress(string: yourWIFPrivateKey) {
                                 
                                    if let key = BTCKey.init(privateKeyAddress: privateKey) {
                                 
                                        print("privateKey = \(key.privateKeyAddress)")
                                 
                                    }
                                 
                                 }`

**Comment by FontaineDenton** [comment]
if let privateKey = BTCPrivateKeyAddress(string: yourWIFPrivateKey) {
                                 
                                    if let key = BTCKey.init(privateKeyAddress: privateKey) {
                                 
                                        print("privateKey = \(key.privateKeyAddress)")
                                 
                                    }
                                 
                                 }

**Comment by topws** [comment]
thks
