### ISSUE TITLE
Full RFC6979 support

### ISSUE THREAD

**Issue by oleganza** [oleganza/CoreBitcoin#18]
Currently BTCKey uses simple HMAC-SHA256 to compute k from private key and tx hash. It works just fine, but it's better to support the "standard" RFC6979 (I simply didn't have enough time to implement it fully).

Pros:

1) Being standard, signatures from different implementations can be audited using the same algorithm.

2) (Not a real benefit) RFC6979 checks if k is out of bounds and sequentially computes next values until they are good. Hitting this case is highly improbable (2^-127 chance).

**Comment by prusnak** [comment]
This C code might be of help:
https://github.com/trezor/trezor-crypto/blob/9fea8f8ab377dc514e40c6fd1f7c89a74c1d8dc6/ecdsa.c#L256

**Comment by oleganza** [comment]
I'm posting a 1 btc bounty for full RFC6979 support (with test vectors, of course).

**Comment by oleganza** [comment]
Done in https://github.com/oleganza/CoreBitcoin/commit/e7f15ab76cc115e6b873f06470adb82e475edb2a

@prusnak kudos for reference implementations.
