### ISSUE TITLE
Payment Requests (BIP 70) Protocol Support

### ISSUE THREAD

**Issue by oleganza** [oleganza/CoreBitcoin#24]
Just adding this here to track this feature.

**Comment by oleganza** [comment]
Merged in https://github.com/oleganza/CoreBitcoin/commit/34a06b7858f93e2894f27aebee6bdb9c27eda2c2

**Comment by jsuder** [comment]
Wow, it's already done? Nice! :+1:

**Comment by oleganza** [comment]
@jsuder yep.
