### ISSUE TITLE
ECIES encryption scheme

### ISSUE THREAD

**Issue by oleganza** [oleganza/CoreBitcoin#27]
Add support for ECIES [like in Bitcore-ECIES](https://github.com/bitpay/bitcore-ecies).

Bounty of 3 BTC placed by @yrashk.

**Comment by oleganza** [comment]
Added basic support for ECIES compatible with Bitcore in a92d38dc1bfd95de201bdd2186b024c2c7f6f4e6. Some API improvements are needed, thought.

**Comment by mackuba** [comment]
Interesting, is there a BIP for this or is this something that only Bitcore implemented before?

**Comment by oleganza** [comment]
@mackuba i couldn't find any precise definition of the algorithm or data encoding to be used with concrete test vectors. Bitcore seems to be choosing a particular set of algorithms (SHA-512, HMAC-SHA256, AES-CBC-256-PKCS7) and otherwise sticking to [ECIES description from Wikipedia](http://en.wikipedia.org/wiki/Integrated_Encryption_Scheme). I needed something "standard" so kept with Bitcore's choice and test vectors.

**Comment by oleganza** [comment]
@mackuba note that I had to [adjust](https://github.com/bitpay/bitcore-ecies/pull/29) Bitcore's implementation with deterministic IV to enable end-to-end test vectors. It's backward-compatible, but now 100% deterministic and blackbox-auditable. And so is CoreBitcoin's implementation.
