### ISSUE TITLE
Cannot build libraries 

### ISSUE THREAD

**Issue by nicolasbigot** [oleganza/CoreBitcoin#71]
For some reason, I cannot build the libraries on Mac OS 10.11 and XCode 7.1.1.
After running `update_openssl.sh` and `build_libraries.sh`, the build only create a full framework for OS X. The iOS framework is incomplete due to build errors.

**Comment by nicolasbigot** [comment]
It looks like it's related to bitcode being disabled for OpenSSL libs but enabled for CoreBitcoin frameworks.

**Comment by oleganza** [comment]
I think long-term we need to migrate from OpenSSL to libsecp256k1 which hopefully will be easier to adopt for bitcode support (https://github.com/oleganza/CoreBitcoin/issues/30)

**Comment by nicolasbigot** [comment]
Any workaround regarding the scripts file to pass compilation?
Maybe flagging `ENABLE_BITCODE` to `NO` would do the trick in the xcodeproj file.

**Comment by oleganza** [comment]
ENABLE_BITCODE=NO will definitely help.

**Comment by brunophilipe** [comment]
I suggest now enabling Bitcode by default:

Using `IPHONEOS_GCC="${DEVELOPER}/usr/bin/gcc -fembed-bitcode"` in the openssl script, and enabling Bitcode for the iOS targets in Xcode makes it compile successfully for me! 😊
